{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "swiggy-clone.fullname" . }}-default-deny
  labels:
    {{- include "swiggy-clone.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "swiggy-clone.fullname" . }}-allow
  labels:
    {{- include "swiggy-clone.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "swiggy-clone.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
  egress:
    # DNS
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    # PostgreSQL (RDS)
    - ports:
        - port: 5432
          protocol: TCP
    # Redis (ElastiCache)
    - ports:
        - port: 6379
          protocol: TCP
    # Kafka (MSK) — TLS
    - ports:
        - port: 9094
          protocol: TCP
    # HTTPS (OpenSearch, AWS APIs, external services)
    - ports:
        - port: 443
          protocol: TCP
{{- end }}
