apiVersion: v1
kind: Service
metadata:
  name: swiggy-clone-api
  namespace: swiggy-clone
  labels:
    app.kubernetes.io/name: swiggy-clone-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: swiggy-clone-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
