apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swiggy-clone-api
  namespace: swiggy-clone
  labels:
    app.kubernetes.io/name: swiggy-clone-api
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: PLACEHOLDER_ACM_CERT_ARN
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: "8080"
    # WebSocket / SignalR sticky sessions
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=86400
spec:
  rules:
    - host: api.swiggy-clone.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swiggy-clone-api
                port:
                  number: 8080
